version: "3.4"
services:
  dev-env-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-env-dev
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /app

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend-dev
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: img-upload
        target: /app/upload

volumes:
  img-upload:
