version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"

  backend:
    build:
      context: ../
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
