version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - dev-env-vol:/app/src

  backend:
    build:
      context: ../
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
volumes:
  dev-env-vol:
